FROM mcr.microsoft.com/dotnet/core/sdk:5.0-alpine

CMD ["dotnet", "test", "/app/tests/tests.csproj"]

COPY agrix.csproj /app/agrix.csproj
RUN dotnet restore /app/agrix.csproj
COPY tests/tests.csproj /app/tests/tests.csproj
RUN dotnet restore /app/tests/tests.csproj

COPY . /app
RUN dotnet build -c Debug /app/agrix.csproj --no-restore
RUN dotnet build -c Debug /app/tests/tests.csproj
