stages:
  - test

run-tests:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:5.0-alpine
  services:
    - docker:dind
  variables:
    MOCK_HOST: docker
  script:
    - dotnet build tests/tests.csproj
    - dotnet test tests/tests.csproj

test-build-test-image:
  stage: test
  image: okinta/podman
  script:
    - podman --storage-driver vfs --cgroup-manager=cgroupfs build -t agrix-tests -f containers/tests/Containerfile .

test-build-image:
  stage: test
  image: okinta/podman
  script:
    - podman --storage-driver vfs --cgroup-manager=cgroupfs build -t okinta/agrix -f containers/agrix/Containerfile .
