image: okinta/podman

stages:
  - test

run-tests:
  stage: test
  script:
    - podman --storage-driver vfs --cgroup-manager=cgroupfs build -t agrix-tests -f containers/tests/Containerfile .
    - podman --storage-driver vfs --cgroup-manager=cgroupfs run agrix-tests

test-build-image:
  stage: test
  script:
    - podman --storage-driver vfs --cgroup-manager=cgroupfs build -t okinta/agrix -f containers/agrix/Containerfile .
