image: buildah/buildah
variables:
  STORAGE_DRIVER: vfs

stages:
  - test

run-tests:
  stage: test
  script:
    - podman build -t agrix-tests -f containers/tests/Containerfile .
    - podman run agrix-tests

test-build-image:
  stage: test
  script:
    - podman build -t okinta/agrix -f containers/agrix/Containerfile .
