image: docker

services:
  - docker:dind

stages:
  - test

run-tests:
  stage: test
  script:
    - docker build -t agrix-tests -f containers/tests/Containerfile .
    - docker run agrix-tests

test-build-image:
  stage: test
  script:
    - docker build -t okinta/agrix -f containers/agrix/Containerfile .
