name: Run tests and publish

on:
  - push
  - pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build test image
        run: buildah bud -t agrix-tests -f containers/tests/Containerfile .
      - name: Run tests
        run: podman run agrix-tests

  test-build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build agrix image
        run: buildah bud -t okinta/agrix -f containers/agrix/Containerfile .

  publish:
    needs:
      - run-tests
      - test-build-image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: okinta/agrix
          tags: latest
          dockerfile: containers/agrix/Containerfile
