name: Run tests

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: okinta/podman-action@v1
      - uses: actions/checkout@v2
      - name: Build test image
        run: buildah bud -t agrix-tests -f containers/tests/Containerfile .
      - name: Run tests
        run: podman run agrix-tests

  test-build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: okinta/podman-action@v1
      - uses: actions/checkout@v2
      - name: Build agrix image
        run: buildah bud -t okinta/agrix -f containers/agrix/Containerfile .
